# 更改后请重启以生效

# 是否启用。
# 为false时自动退出
#enabled: false
enabled: true

# maxSizeMB 用于指定允许处理的文件的最大大小，单位为兆字节（MB）。
# 当扫描文件时，如果文件大小超过该值，将跳过该文件不进行处理。
# 若设置为 -1，则表示不限制文件大小。
maxSizeMB: 1024

# targetDir 表示文件复制的目标目录。
# 当扫描到符合正则表达式模式的文件时，会将这些文件复制到该目录下。
# 请确保该目录存在且有写入权限。
targetDir: "./target"

# regexPatterns 是一个字符串列表，其中每个字符串都是一个正则表达式模式。
# 在扫描文件时，会对文件名进行正则匹配，只要文件名满足其中一个正则表达式，该文件就会被处理（复制到目标目录）。
# 文件名使用Linux风格，即使用“/”作为路径分隔符。
# 比如：
# - ".*" # 匹配任意文件
# - ".*\.txt$" # 匹配所有以 .txt 结尾的文件
#
# 正则表达式语法简要说明：
# ^ 匹配行首
# $ 匹配行尾
# . 匹配任意单个字符
# \d 匹配数字，\w 匹配单词字符（含下划线）
# [abc] 匹配 a/b/c 中的任意一个字符
# [^abc] 匹配非 a/b/c 的任意字符
# .* 匹配0或多个任意字符（贪婪模式）
# \\d{3} 精确匹配3个数字（注意需要双反斜杠）
# a+ 匹配1个及以上数量的a
regexPatterns:
  - ".*"
